// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesMgmntApp.Data;

#nullable disable

namespace SalesMgmntApp.Migrations
{
    [DbContext(typeof(BirdsMgmntDbContext))]
    [Migration("20230116074002_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesMgmntApp.Entities.Bird", b =>
                {
                    b.Property<int>("BirdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BirdId"));

                    b.Property<string>("BirdName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BloodLineId")
                        .HasColumnType("int");

                    b.Property<string>("BredFor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Breeder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ColourId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("DamRingMark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DamRingNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DamRingYr")
                        .HasColumnType("int");

                    b.Property<string>("Eye_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBP")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOLR")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRace")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSOH")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStock")
                        .HasColumnType("bit");

                    b.Property<string>("RingMark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RingNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RingYr")
                        .HasColumnType("int");

                    b.Property<string>("SireRingMark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SireRingNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SireRingYr")
                        .HasColumnType("int");

                    b.HasKey("BirdId");

                    b.ToTable("Birds");
                });

            modelBuilder.Entity("SalesMgmntApp.Entities.BloodLine", b =>
                {
                    b.Property<int>("BloodLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BloodLineId"));

                    b.Property<string>("BloodLineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("BloodLineId");

                    b.ToTable("BloodLines");
                });
#pragma warning restore 612, 618
        }
    }
}
